"""transactional tables

Revision ID: 6723188cc924
Revises: 9c02d0b6e56b
Create Date: 2026-08-23 09:10:57.972788

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6723188cc924"
down_revision: str | Sequence[str] | None = "9c02d0b6e56b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("username", name=op.f("uq_students_username")),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "COMPLETED", name="attempt_status"), nullable=False),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_attempts_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_attempts_student_id_students")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    op.create_index(op.f("ix_attempts_paper_id"), "attempts", ["paper_id"], unique=False)
    op.create_index(op.f("ix_attempts_student_id"), "attempts", ["student_id"], unique=False)
    op.create_table(
        "sub_part_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("sub_part_id", sa.Integer(), nullable=False),
        sa.Column("marks_scored", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "marks_scored >= 0", name=op.f("ck_sub_part_results_marks_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("fk_sub_part_results_attempt_id_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["sub_part_id"],
            ["sub_parts.id"],
            name=op.f("fk_sub_part_results_sub_part_id_sub_parts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_part_results")),
        sa.UniqueConstraint("attempt_id", "sub_part_id", name="result_identity"),
    )
    op.create_index(
        op.f("ix_sub_part_results_attempt_id"), "sub_part_results", ["attempt_id"], unique=False
    )
    op.create_index(
        op.f("ix_sub_part_results_sub_part_id"), "sub_part_results", ["sub_part_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_part_results_sub_part_id"), table_name="sub_part_results")
    op.drop_index(op.f("ix_sub_part_results_attempt_id"), table_name="sub_part_results")
    op.drop_table("sub_part_results")
    op.drop_index(op.f("ix_attempts_student_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_paper_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("students")
    # ### end Alembic commands ###
