"""reference tables

Revision ID: 9c02d0b6e56b
Revises: 
Create Date: 2026-08-21 18:28:17.994775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c02d0b6e56b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('board', 'code', name='subject_identity')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('session', sa.Enum('MARCH', 'MAY_JUNE', 'OCT_NOV', name='exam_session'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.CheckConstraint('total_marks > 0', name=op.f('ck_papers_total_marks_positive')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_papers_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('subject_id', 'component', 'variant', 'session', 'year', name='paper_identity')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('subject_id', 'name', name='topic_name')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_questions_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('paper_id', 'question_number', name='question_number')
    )
    op.create_table('sub_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_marks > 0', name=op.f('ck_sub_parts_max_marks_positive')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_sub_parts_question_id_questions')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_sub_parts_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_parts')),
    sa.UniqueConstraint('question_id', 'label', name='sub_part_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_parts')
    op.drop_table('questions')
    op.drop_table('topics')
    op.drop_table('papers')
    op.drop_table('subjects')
    # ### end Alembic commands ###
